version: '3'
services:
  postgres:
    image: "postgres:10.4-alpine"
    container_name: minorwebdev_postgres
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=minorwebdev
      - POSTGRES_PASSWORD=faberyayo
  adminer:
    image: adminer
    restart: always
    container_name: minorwebdev_adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes: 
  pgdata: